# 롤 API 데이터 수집하기

In [208]:
import requests
import json
import time
import numpy as np
import pandas as pd

## API를 통한 소환사 정보 수집

In [209]:
# Lol Api에서 소환사 명을 통해서 게임 정보를 알 수 있는 puuid 불러오기 
summoner_Name = 'one summer drive' #소환사명
api_key = "RGAPI-fa3757e6-edbf-4e39-8001-14e03ad13b01" # api key
request_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept-Charset": "application/x-www-form-urlencoded; charset=UTF-8",
    "Origin": "https://developer.riotgames.com",
    "X-Riot-Token": "RGAPI-fa3757e6-edbf-4e39-8001-14e03ad13b01"
}

summoner_url="https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/"+summoner_Name+"/""?api_key="+api_key

In [210]:
# requests를 통해서 puuid 추출하기
def summoner(summoner_Name, api_key):
    summoner_url = "https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/"+summoner_Name+"/""?api_key="+api_key
    return requests.get(summoner_url, headers=request_headers).json()['puuid']
summoner_puuid = summoner(summoner_Name, api_key)
summoner_puuid

'cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72J0XfluBWZsNURa-_rKA5AR_vMndVW8tg'

In [211]:
# match id를 확인할 수 있는 api를 통해서 조회하기
# match_count : 조회하고 싶은 매치의 수
# 더 많이 조회를 하고 싶으나 횟수 제한이 있다. (100) 이번 시즌 내가 플레이한 62게임에 대해서 조사하기 
def match(summoner_puuid, match_count):
    match_url = "https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/"+summoner_puuid+"/ids?start=0&count="+str(match_count)
    return requests.get(match_url, headers=request_headers).json()
match_id = match(summoner_puuid, 90)
match_id

['KR_6017207879',
 'KR_6017033024',
 'KR_6016828310',
 'KR_6016772762',
 'KR_6016770544',
 'KR_6016651859',
 'KR_6016575318',
 'KR_6015787618',
 'KR_6015488822',
 'KR_6015088138',
 'KR_6014287649',
 'KR_6012864614',
 'KR_6012476838',
 'KR_6011712595',
 'KR_6011597486',
 'KR_6010856241',
 'KR_6009908963',
 'KR_6009876008',
 'KR_6009892943',
 'KR_6009828517',
 'KR_6009775487',
 'KR_6009753833',
 'KR_6008388001',
 'KR_6008101825',
 'KR_6007718428',
 'KR_6007632404',
 'KR_6007543140',
 'KR_6007407898',
 'KR_6007030534',
 'KR_6006751091',
 'KR_6006310180',
 'KR_6006082114',
 'KR_6005589922',
 'KR_6005521617',
 'KR_6005292412',
 'KR_6004906534',
 'KR_6002949666',
 'KR_6002335329',
 'KR_6000663825',
 'KR_6000095173',
 'KR_5995456456',
 'KR_5993880535',
 'KR_5992325428',
 'KR_5992263876',
 'KR_5992247758',
 'KR_5992174929',
 'KR_5992139509',
 'KR_5992067375',
 'KR_5990749357',
 'KR_5990208811',
 'KR_5989449386',
 'KR_5984608595',
 'KR_5983799498',
 'KR_5975922818',
 'KR_5972653802',
 'KR_5971831750',
 'KR_5970907653',
 'KR_5969417133',
 'KR_5968292187',
 'KR_5967746336',
 'KR_5966881810',
 'KR_5964412484',
 'KR_5962150235',
 'KR_5960271629',
 'KR_5959453245',
 'KR_5958843905',
 'KR_5958560539',
 'KR_5957375473',
 'KR_5957281387',
 'KR_5955747139',
 'KR_5948189793',
 'KR_5948144099',
 'KR_5948039621',
 'KR_5948044438',
 'KR_5939314712',
 'KR_5939331684',
 'KR_5939189304',
 'KR_5939205118',
 'KR_5939202377',
 'KR_5939160666',
 'KR_5938908305',
 'KR_5938915547',
 'KR_5938942370',
 'KR_5938860084',
 'KR_5932891566',
 'KR_5932826930',
 'KR_5932814225',
 'KR_5932759611',
 'KR_5932679359',
 'KR_5919442072']

In [212]:
# 게임 세부내용 불러오기
# 조회는 하나씩만 가능하므로 for문이나 while문을 돌려 하나씩 조회한다.
def game(match_id_num):
    game_url = "https://asia.api.riotgames.com/lol/match/v5/matches/"+match_id_num
    return requests.get(game_url, headers=request_headers).json()['info']['participants']

## 분석에 사용할 90개의 데이터 수집하여 데이터 프레임 생성
- 100개로 하고 돌렸으나 API응답문제가 발생하였다

In [216]:
#Future Warning 메세지 제거하기
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# 게임 데이터를 담을 DataFrame 생성하기
game_df = pd.DataFrame(columns=['puuid', 'teamPosition', 'individualPosition', 'champName', 'champExp', 'summoner_spell1', 'summoner_spell2' ,
                                'kills', 'deaths', 'assists', 'damageDealtToBuildings', 'totalDamageDealtToChamp', 'damagePerMin', 'teamDamagePer(%)',
                                'killParticipation(%)', 'totalDamageTaken', 'damageTakeOnTeamPer(%)', 'goldEarned', 'goldPerMin', 'totalCs',
                                'maxCsAdvantageOnLaneOpponent', 'maxLevelLeadLaneOpponent', 'gameEndedInEarlySurren', 'gameEndedInSurren',
                                'teamEarlySurrn', 'timePlayed'])

for i in range(len(match_id)):
    print(i)
    game_content = game(match_id[i])
    for j in range(len(game_content)):
        try:
            input_data = {

                'puuid':game_content[j]['puuid'], 
                'teamPosition':game_content[j]['teamPosition'], 
                'individualPosition':game_content[j]['individualPosition'], 
                'champName':game_content[j]['championName'], 
                'champExp':float(game_content[j]['champExperience']), 
                'summoner_spell1':float(game_content[j]['summoner1Id']), 
                'summoner_spell2':float(game_content[j]['summoner2Id']),
                'kills':float(game_content[j]['kills']), 
                'deaths':float(game_content[j]['deaths']), 
                'assists':float(game_content[j]['assists']), 
                'damageDealtToBuildings':float(game_content[j]['damageDealtToBuildings']), 
                'totalDamageDealtToChamp':float(game_content[j]['totalDamageDealtToChampions']),
                'damagePerMin':game_content[j]['challenges']['damagePerMinute'], 
                'teamDamagePer(%)':round(game_content[j]['challenges']['teamDamagePercentage'], 2)*100,
                'killParticipation(%)':game_content[j]['challenges']['killParticipation']*100,
                'totalDamageTaken':float(game_content[j]['totalDamageTaken']),
                'damageTakeOnTeamPer(%)':round(game_content[j]['challenges']['damageTakenOnTeamPercentage'],2)*100,
                'goldEarned':float(game_content[j]['goldEarned']),
                'goldPerMin':game_content[j]['challenges']['goldPerMinute'],
                'totalCs':float(game_content[j]['totalMinionsKilled']+game_content[j]['neutralMinionsKilled']),
                'maxCsAdvantageOnLaneOpponent':float(game_content[j]['challenges']['maxCsAdvantageOnLaneOpponent']),
                'maxLevelLeadLaneOpponent':float(game_content[j]['challenges']['maxLevelLeadLaneOpponent']),
                'gameEndedInEarlySurren':game_content[j]['gameEndedInEarlySurrender'],
                'gameEndedInSurren':game_content[j]['gameEndedInSurrender'],
                'teamEarlySurrn':game_content[j]['teamEarlySurrendered'],
                'timePlayed':float(round(game_content[j]['timePlayed']/60,2)*100) # 4자리로 앞의 2자리는 분, 뒤의 2자리는 초로 구성되어있다. 
                }
            game_df = game_df.append(input_data, ignore_index=True)
        except:
            input_data = {

                'puuid':game_content[j]['puuid'], 
                'teamPosition':game_content[j]['teamPosition'], 
                'individualPosition':game_content[j]['individualPosition'], 
                'champName':game_content[j]['championName'], 
                'champExp':float(game_content[j]['champExperience']), 
                'summoner_spell1':float(game_content[j]['summoner1Id']), 
                'summoner_spell2':float(game_content[j]['summoner2Id']),
                'kills':float(game_content[j]['kills']), 
                'deaths':float(game_content[j]['deaths']), 
                'assists':float(game_content[j]['assists']), 
                'damageDealtToBuildings':float(game_content[j]['damageDealtToBuildings']), 
                'totalDamageDealtToChamp':float(game_content[j]['totalDamageDealtToChampions']),
                'damagePerMin':game_content[j]['challenges']['damagePerMinute'], 
                'teamDamagePer(%)':round(game_content[j]['challenges']['teamDamagePercentage'], 2)*100,
                'killParticipation(%)':game_content[j]['challenges']['killParticipation']*100,
                'totalDamageTaken':float(game_content[j]['totalDamageTaken']),
                'damageTakeOnTeamPer(%)':round(game_content[j]['challenges']['damageTakenOnTeamPercentage'],2)*100,
                'goldEarned':float(game_content[j]['goldEarned']),
                'goldPerMin':game_content[j]['challenges']['goldPerMinute'],
                'totalCs':float(game_content[j]['totalMinionsKilled']+game_content[j]['neutralMinionsKilled']),
                'maxCsAdvantageOnLaneOpponent':0,
                'maxLevelLeadLaneOpponent':0,
                'gameEndedInEarlySurren':game_content[j]['gameEndedInEarlySurrender'],
                'gameEndedInSurren':game_content[j]['gameEndedInSurrender'],
                'teamEarlySurrn':game_content[j]['teamEarlySurrendered'],
                'timePlayed':float(round(game_content[j]['timePlayed']/60,2)*100) # 4자리로 앞의 2자리는 분, 뒤의 2자리는 초로 구성되어있다. 
                }
            game_df = game_df.append(input_data, ignore_index=True)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89

In [217]:
game_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   puuid                         900 non-null    object
 1   teamPosition                  900 non-null    object
 2   individualPosition            900 non-null    object
 3   champName                     900 non-null    object
 4   champExp                      900 non-null    float64
 5   summoner_spell1               900 non-null    float64
 6   summoner_spell2               900 non-null    float64
 7   kills                         900 non-null    float64
 8   deaths                        900 non-null    float64
 9   assists                       900 non-null    float64
 10  damageDealtToBuildings        900 non-null    float64
 11  totalDamageDealtToChamp       900 non-null    float64
 12  damagePerMin                  900 non-null    float64
 13  teamDamagePer(%)              900 non-null    float64
 14  killParticipation(%)          900 non-null    float64
 15  totalDamageTaken              900 non-null    float64
 16  damageTakeOnTeamPer(%)        900 non-null    float64
 17  goldEarned                    900 non-null    float64
 18  goldPerMin                    900 non-null    float64
 19  totalCs                       900 non-null    float64
 20  maxCsAdvantageOnLaneOpponent  900 non-null    float64
 21  maxLevelLeadLaneOpponent      900 non-null    float64
 22  gameEndedInEarlySurren        900 non-null    object
 23  gameEndedInSurren             900 non-null    object
 24  teamEarlySurrn                900 non-null    object
 25  timePlayed                    900 non-null    float64
dtypes: float64(19), object(7)
memory usage: 182.9+ KB

In [218]:
game_df

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,damageTakeOnTeamPer(%),goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timePlayed
0,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Akali,17035.0,4.0,12.0,5.0,10.0,4.0,...,19.0,11279.0,292.662528,167.0,3.00,0.0,False,False,False,3853.0
1,ef8EdZNmTuHH49lNib4mUFIWu-a60p8EvU-K1e9dzXXHQn...,JUNGLE,JUNGLE,Taliyah,17337.0,11.0,4.0,3.0,11.0,7.0,...,21.0,13305.0,345.221804,219.0,40.30,1.0,False,False,False,3853.0
2,4QnucqF7Qx3g6qdDWKZm8naW8QU2rIU11xPOcMRq5XbjFm...,MIDDLE,MIDDLE,Yone,19124.0,14.0,4.0,9.0,10.0,8.0,...,20.0,16345.0,424.098371,237.0,96.00,1.0,False,False,False,3853.0
3,aOAvT9veq32BJqJZaAv4RU9SZS5pkeNXjZKT9VzQD9j8m0...,BOTTOM,BOTTOM,Kalista,17249.0,7.0,4.0,13.0,9.0,8.0,...,25.0,18717.0,485.660739,284.0,62.80,2.0,False,False,False,3853.0
4,eqzWrrEr4D_zWSjTyf3VDSvffdonhAUGA2VqTHu46QD3YO...,UTILITY,UTILITY,MissFortune,14933.0,4.0,3.0,3.0,9.0,15.0,...,15.0,12123.0,314.549904,58.0,26.40,3.0,False,False,False,3853.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,YYD-vZSBRgTjGuiw6PFuQBkq_jWg4Gs1qd3QMNzxfpNnBS...,TOP,TOP,Nasus,15778.0,4.0,12.0,6.0,4.0,4.0,...,29.0,12352.0,399.182742,192.0,35.05,2.0,False,False,False,3093.0
896,2Oz57YFmjbhaQ901AdAur8KCg_Yrihi6Q43hA66isY2Zdi...,JUNGLE,JUNGLE,Vi,13183.0,11.0,4.0,7.0,11.0,9.0,...,19.0,11292.0,364.925387,115.0,3.00,1.0,False,False,False,3093.0
897,pEl9IfL_Dvj7AVHiYUxXGONzTJkYe02DkHRhx7soMjA3Tt...,MIDDLE,MIDDLE,Yasuo,9266.0,14.0,4.0,0.0,15.0,2.0,...,18.0,7362.0,237.938166,106.0,1.00,0.0,False,False,False,3093.0
898,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Jhin,12242.0,4.0,7.0,7.0,6.0,7.0,...,14.0,13746.0,444.223697,189.0,17.00,1.0,False,False,False,3093.0
899,GUAe7Jq7-2ZVXBRX1uwaXr_zzq9d_HHQ0mpMIk1ImsC_Gu...,UTILITY,UTILITY,Swain,11050.0,14.0,4.0,4.0,12.0,5.0,...,20.0,8337.0,269.445539,36.0,6.50,1.0,False,False,False,3093.0

## 가설 확인하기

```
인게임 속의 트롤링은 처음부터 발생할 수도 있고 중간에 소환사의 변심으로 인해서 발생할 수도 있고 수 많은 경우로 인해 발생한다.
기본적으로 의도적인 죽음, 다른 소환사들 방해, 한타에 합류를 하지 않거나, 우물에서 잠수를 하거나 
위와 같은 행위들은 기본적으로 DPM의 하락을 가져온다. 또한 안정적으로 성장을 한 상대 라이너에 비해서 성장 측면에서 많은 차이가 나타난다. 

픽창에서의 싸움으로 인한 소환사 스펠, 주 포지션이 아니므로 인한 트롤 등에 대해서는 소환사 스펠을 통해서 확인한다. 
```

- 가장 최근 게임의 트롤은 워익이었다. 
- 욕설과 함께 한타참여X, 정글링만 하거나, 우물에서 잠수 
- 딜량에 대해서 수치화 하기 
- 게임은 빠른 서렌이 나오는 15분부터 끝나기 시작한다.
- 15분까지는 기본적으로 라인전이 끝나는 시기, 탑, 미드, 바텀의 경우에는 라인전을 통해서 딜량을 쌓을수 있으나 정글의 경우에는 힘들다. 
- 게임이 장기간으로 가는경우 서포터는 딜량이 작기 마련이다. 
- 원딜의 경우에는 코어가 뜨면 뜰 수록 강해진다. 
- 위와 같은 경우를 수치화 조정해서 딜량을 계산한다.

## Match에 포함되어 있는 칼바람, 일반게임 정보 제거하기

In [136]:
# 포지션에 Top, Jungle, Middle, Botoom, Utility 이외의 공백인 행들이 일반게임, 칼바람나락의 결과
game_df['teamPosition'].unique()

array(['TOP', 'JUNGLE', 'MIDDLE', 'BOTTOM', 'UTILITY', ''], dtype=object)

In [163]:
game_df['teamPosition']==''.index

0      False
1      False
2      False
3      False
4      False
       ...
895    False
896    False
897    False
898    False
899    False
Name: teamPosition, Length: 900, dtype: bool

In [169]:
# 포지션 선택이 없는 게임 제거하기
# 29게임이 제외되었다. 
game_df = game_df.drop(game_df[game_df['teamPosition']==''].index, axis=0).reset_index(drop=True)
game_df

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timeplayed,timePlayed
0,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Akali,17035,4,12,5,10,4,...,11279,292.662528,167,3,0,False,False,False,NaN,3853.0
1,ef8EdZNmTuHH49lNib4mUFIWu-a60p8EvU-K1e9dzXXHQn...,JUNGLE,JUNGLE,Taliyah,17337,11,4,3,11,7,...,13305,345.221804,219,40.3,1,False,False,False,NaN,3853.0
2,4QnucqF7Qx3g6qdDWKZm8naW8QU2rIU11xPOcMRq5XbjFm...,MIDDLE,MIDDLE,Yone,19124,14,4,9,10,8,...,16345,424.098371,237,96.0,1,False,False,False,NaN,3853.0
3,aOAvT9veq32BJqJZaAv4RU9SZS5pkeNXjZKT9VzQD9j8m0...,BOTTOM,BOTTOM,Kalista,17249,7,4,13,9,8,...,18717,485.660739,284,62.8,2,False,False,False,NaN,3853.0
4,eqzWrrEr4D_zWSjTyf3VDSvffdonhAUGA2VqTHu46QD3YO...,UTILITY,UTILITY,MissFortune,14933,4,3,3,9,15,...,12123,314.549904,58,26.4,3,False,False,False,NaN,3853.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,YYD-vZSBRgTjGuiw6PFuQBkq_jWg4Gs1qd3QMNzxfpNnBS...,TOP,TOP,Nasus,15778,4,12,6,4,4,...,12352,399.182742,192,35.05,2,False,False,False,NaN,3093.0
606,2Oz57YFmjbhaQ901AdAur8KCg_Yrihi6Q43hA66isY2Zdi...,JUNGLE,JUNGLE,Vi,13183,11,4,7,11,9,...,11292,364.925387,115,3,1,False,False,False,NaN,3093.0
607,pEl9IfL_Dvj7AVHiYUxXGONzTJkYe02DkHRhx7soMjA3Tt...,MIDDLE,MIDDLE,Yasuo,9266,14,4,0,15,2,...,7362,237.938166,106,1,0,False,False,False,NaN,3093.0
608,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Jhin,12242,4,7,7,6,7,...,13746,444.223697,189,17,1,False,False,False,NaN,3093.0
609,GUAe7Jq7-2ZVXBRX1uwaXr_zzq9d_HHQ0mpMIk1ImsC_Gu...,UTILITY,UTILITY,Swain,11050,14,4,4,12,5,...,8337,269.445539,36,6.5,1,False,False,False,NaN,3093.0

### Play시간대 별로 나누기

#### 20분 이내 종료된 게임

In [170]:
# 5게임만이 61게임중에서 빠르게 끝난 게임 
game_played20down = game_df[game_df['timePlayed']<2000].reset_index(drop=True)
game_played20down

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timeplayed,timePlayed
0,9yf8Rs_z-wYgmGrOEt3c5Dxt5vxXciWjSutOB3cJe_X5_b...,TOP,TOP,Jax,6558,12,4,2,7,0,...,5036,320.051088,80,1,0,False,True,False,NaN,1573.0
1,VUCm_CvzaECN6ltgCfgnj4tPkV98sMcR0qOK-Fe72GKuRm...,JUNGLE,JUNGLE,RekSai,5310,11,4,2,2,2,...,4776,303.528755,70,0,0,False,True,False,NaN,1573.0
2,CyTdqikqKhul9jBHBoUm08M8f29sDoPbnjfSeBq1bdP3h_...,MIDDLE,MIDDLE,Vex,7538,4,14,4,2,3,...,6589,418.764576,91,41,4,False,True,False,NaN,1573.0
3,861oCjkJqJ0Px5b1qomocugo1AVxsEQCO125KUAe2_ks8x...,BOTTOM,BOTTOM,MissFortune,5804,7,4,3,0,2,...,6060,385.147985,114,7,1,False,True,False,NaN,1573.0
4,0DZwozk2_QL_6JM7JdXg_P2DDtIRsiazbcb2KRGZdrJbn-...,UTILITY,UTILITY,Blitzcrank,5272,4,3,1,1,4,...,4161,264.481713,22,10,1,False,True,False,NaN,1573.0
5,qgPQotn5woPPNGVWHTMKkNsxSO15eUKgKArQWn2D06bxpW...,TOP,TOP,Darius,8809,4,6,8,2,0,...,7298,463.812662,117,45,3,False,True,False,NaN,1573.0
6,c3PQr4ImXyUqbkgaZzE-V8V-MnByQjA37QG5o7LfQknS5B...,JUNGLE,JUNGLE,Kayn,7686,11,4,2,2,3,...,6618,420.571086,118,50.0,2,False,True,False,NaN,1573.0
7,IeIOTtJf8Oisc_iGCJWABPZXIpCmA9bNNYKIIIyI_-a5R6...,MIDDLE,MIDDLE,Katarina,3969,14,12,2,4,1,...,4159,264.319990,50,8,1,False,True,False,NaN,1573.0
8,tg4UHF9QI9Z3SgiNekYIiyf2c9rHc2IKBdwYlaHdAvajTE...,BOTTOM,BOTTOM,Ezreal,4795,7,4,0,2,0,...,4611,293.043398,111,21,1,False,True,False,NaN,1573.0
9,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,UTILITY,UTILITY,Ashe,4859,4,3,0,2,0,...,3449,219.203407,30,8,1,False,True,False,NaN,1573.0
10,yKZnzbQCJcT-VAKRYJSFdo_wn8SGREc6G4yiCOdiRRkJEH...,TOP,TOP,Darius,6800,6,4,2,1,0,...,5289,347.043530,116,38,1,False,True,False,NaN,1523.0
11,OsztWsPxdeH1iVT7J1AQdehdZFD3r1j5Q65zNsScVjTO_Q...,JUNGLE,JUNGLE,FiddleSticks,5856,11,4,1,3,3,...,5195,340.854404,90,20.4,2,False,True,False,NaN,1523.0
12,xVsyNZGxPGLSPVfYOanwEcUGgWEm_VpJ03mKQM24vDSSc7...,MIDDLE,MIDDLE,Sylas,4778,14,4,1,3,1,...,3333,218.711673,34,0,1,False,True,False,NaN,1523.0
13,rJVOFvAuLuTGfSwQKiQePeI0nHB9cbrihrj5oiYb-zkjpt...,BOTTOM,BOTTOM,Xayah,3114,7,4,1,6,0,...,3252,213.375420,44,0,0,False,True,False,NaN,1523.0
14,vMFoGttVCWb_L0UH_-IrwA_1UGwaB45mE9-KmpNvknpNh9...,UTILITY,UTILITY,Yuumi,3517,14,3,0,3,2,...,3099,203.388031,5,1,0,False,True,False,NaN,1523.0
15,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Akali,6456,4,12,0,2,2,...,4409,289.324512,87,0,1,False,True,False,NaN,1523.0
16,mBoisLx7cBhtHNJGa1EVPdt2znZjHYAfhYW0UP-wV8SvNp...,JUNGLE,JUNGLE,Talon,5469,4,11,0,1,4,...,4758,312.198851,82,2.4,1,False,True,False,NaN,1523.0
17,tcIS0GLcneCiAW4NwjZb7VsSdleY435ImtRJikBi_vsjTM...,MIDDLE,MIDDLE,Lux,9434,4,7,7,1,0,...,7436,487.909286,130,96,4,False,True,False,NaN,1523.0
18,GC61YndofrH7zJEskIC6By2239u8zg7V2JvIerOkKxoWnJ...,BOTTOM,BOTTOM,Lucian,6368,4,7,9,0,0,...,8716,571.881267,123,79,4,False,True,False,NaN,1523.0
19,k9jheBEp3iNLwcHbeNf68ppVlCPwx-mG_97IWidYeus2QP...,UTILITY,UTILITY,Nami,4792,14,4,0,1,8,...,4587,301.014700,10,6,2,False,True,False,NaN,1523.0
20,nxp0FYb8Bm2X7Is7P_8t_LytQBIIU-48MqPrBgruO4dVeX...,TOP,TOP,Kayle,10480,12,4,2,1,0,...,7990,409.279655,154,36,1,False,True,False,NaN,1952.0
21,nNNLQ9ep-05WYcCktuee1yPkKoJArsZfjz-jewYiXP8310...,JUNGLE,JUNGLE,XinZhao,8740,4,11,4,0,5,...,8014,410.500117,109,17.75,2,False,True,False,NaN,1952.0
22,vyNBPW8FqdzdM5mRglOnlWc_rNOpsJdWozP_XFGNkrkusk...,MIDDLE,MIDDLE,Ahri,9627,14,4,4,1,3,...,7960,407.711944,131,31,2,False,True,False,NaN,1952.0
23,fBc7j9IjOXOupOnN4UFWcNZ0yD9ZAVcUjsooQU8-cBP_JK...,BOTTOM,BOTTOM,Kaisa,8049,7,4,5,1,7,...,9036,462.822230,138,8,2,False,True,False,NaN,1952.0
24,utdh9SrrlLE4o-xkJbNVuyp2CRRW5kwkJuKEanF0KfL5L_...,UTILITY,UTILITY,Sylas,7011,14,4,5,2,5,...,7211,369.370757,26,7,2,False,True,False,NaN,1952.0
25,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Gangplank,8837,4,12,1,2,0,...,5923,303.391759,118,7,1,False,True,False,NaN,1952.0
26,sa7tciOemv-8u9L4U4QkKFAQr4usIm1g-kpPz2taJs0kpL...,JUNGLE,JUNGLE,Warwick,6319,4,11,1,4,1,...,5517,282.597147,92,11.0,1,False,True,False,NaN,1952.0
27,ouwnU00p3VVAHZTOQE5ATOb5CWLX0cNh2Uty74UejyKlHX...,MIDDLE,MIDDLE,Xerath,7424,1,4,0,4,0,...,5037,257.990071,101,0,0,False,True,False,NaN,1952.0
28,yo7QnFk5PU5C_1HrguUgJmhyOUS1EDwUwNjBZXGVJw2vAB...,BOTTOM,BOTTOM,Ashe,6626,7,4,3,4,1,...,6636,339.910420,137,15,1,False,True,False,NaN,1952.0
29,rnBD6bHESO4YDkYUvCoqrTzLSSJPBayfyT-eDUv-WuXfxL...,UTILITY,UTILITY,Lux,5286,14,4,0,6,4,...,4439,227.370945,19,4,1,False,True,False,NaN,1952.0
30,D58qSu1hYSOnEBJs74qZ5VCt6PymDZOnoCGErGYRUz_NWz...,TOP,TOP,Soraka,7692,12,4,2,4,7,...,5395,285.634450,68,7,2,False,True,False,NaN,1888.0
31,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,JUNGLE,JUNGLE,Graves,7871,4,11,2,2,5,...,6981,369.596626,108,16.0,1,False,True,False,NaN,1888.0
32,w23nDK6_Wg3SJuCz9dtfsUKjzIxm9nh-LRfA_KVLpcmL-K...,MIDDLE,MIDDLE,Akali,9288,14,4,8,4,3,...,8231,435.790877,109,10,2,False,True,False,NaN,1888.0
33,1V3ZUTK6GlxbQ29Kiq_P9E8zsM_qmEPlFDYTiQesGIzL8M...,BOTTOM,BOTTOM,Vayne,8714,7,4,6,1,1,...,9113,482.487775,168,68,2,False,True,False,NaN,1888.0
34,ndlZVwdiXBkjXS9vVZnX1NojZJJxgRW4ZVXzZfXgWFMfO2...,UTILITY,UTILITY,Senna,5871,14,4,1,4,6,...,5500,291.201275,13,0,1,False,True,False,NaN,1888.0
35,5QiWucuMelUIjTolOPSi2MLBaq1br8iHA6cEbw84cKQAww...,TOP,TOP,Tristana,6979,4,14,4,4,0,...,6811,360.623341,100,46,2,False,True,False,NaN,1888.0
36,mxlRrdOUZ5tY4i5mkk8BrQkV1qjiCgFriYSOGleNqtqUFE...,JUNGLE,JUNGLE,Vi,8299,11,4,2,5,7,...,8428,446.188800,116,53.0,2,False,True,False,NaN,1888.0
37,0UwQteZ3PqTXbfPTlBd6QwKQPHdZLH3eeLHMlD1kpKxOOy...,MIDDLE,MIDDLE,Ahri,8601,4,12,5,3,2,...,7440,393.887079,133,69,1,False,True,False,NaN,1888.0
38,HgosqpgdXof_N-zJZJiKxfhKaVz1o_ZwQIuyep07lH5Kv5...,BOTTOM,BOTTOM,Lucian,6927,4,3,3,5,3,...,6871,363.799742,128,64.0,0,False,True,False,NaN,1888.0
39,hLaVvNggTJSb9dPsbN2XCeS2QqELyl7BWnTFlADrKXev7G...,UTILITY,UTILITY,Karma,5365,14,4,1,2,7,...,5182,274.372485,3,0,0,False,True,False,NaN,1888.0
40,xNVvpCgpQj0mniFjcxA9p89FdrbrzjdQag6FxAa6ipVxjV...,TOP,TOP,Kayn,8785,4,12,2,4,0,...,6136,340.620479,100,0,1,False,True,False,NaN,1800.0
41,md0KJGZTQnT2YUYJcV3xcektKlsUbPb371KWcjpgo50i2-...,JUNGLE,JUNGLE,LeeSin,7766,4,11,7,6,2,...,7389,410.166829,79,2,1,False,True,False,NaN,1800.0
42,YP5elJXG5mqiE4MOshazOq50Dl0WD36caWwzXjhWgwZcd4...,MIDDLE,MIDDLE,Yone,6637,14,4,1,7,2,...,4479,248.650538,69,0,0,False,True,False,NaN,1800.0
43,PXW0hYwn9hlRo2fR20P3wdrRRrsgv0RiSuG-Vyy9630ogD...,BOTTOM,BOTTOM,Kaisa,6515,7,4,0,1,1,...,5106,283.451465,127,2,0,False,True,False,NaN,1800.0
44,RhRYqU3r1-cfqx75MFSD4Owvfzbd-JXA_iaj62cfn7Ef_c...,UTILITY,UTILITY,Yuumi,4391,14,3,0,2,4,...,3426,190.162928,1,0,0,False,True,False,NaN,1800.0
45,izkdkzth-nRWiGU1ssUGwGOZSmIx3E0CnVw8TvmCdbADRI...,TOP,TOP,Lucian,10465,12,4,5,2,3,...,9242,512.974362,160,63,2,False,True,False,NaN,1800.0
46,GLUb-YiZWPONWpR3wd4E7w17Qmez0-Zowkk-ZmbdchnAAL...,JUNGLE,JUNGLE,Viego,8087,11,4,5,4,3,...,7629,423.453881,97,28.0,2,False,True,False,NaN,1800.0
47,QOU8VObhOsaqbkB3fo8RhBWfhSnBlA6eL6LN5VMP3rl9I3...,MIDDLE,MIDDLE,Lissandra,9822,12,4,7,1,3,...,8856,491.572199,133,44,2,False,True,False,NaN,1800.0
48,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Jhin,6736,4,7,1,1,6,...,7273,403.683500,147,35,1,False,True,False,NaN,1800.0
49,YJ4oKVU_vs1Afh-O6QxCNWStUres0aHI0jhRMWZ6CBlEYS...,UTILITY,UTILITY,Nautilus,6082,14,4,2,2,3,...,5080,281.968336,29,1,1,False,True,False,NaN,1800.0

#### 20분 ~ 30분 사이 종료된 게임

In [183]:
# 20분에서 30분 사이 종료된 게임으로는 33게임이 존재한다. 
game_played2030 = game_df[(2000<= game_df['timePlayed']) & (game_df['timePlayed'] < 3000)].reset_index(drop=True)
game_played2030

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timeplayed,timePlayed
0,r1mEdSqYA-GlBBYPlXV_uq4ACKssZg0SHp1u0H56snJMsB...,TOP,TOP,Mordekaiser,11967,6,4,5,1,0,...,7839,386.875311,150,39,2,False,True,False,NaN,2022.0
1,1gA6H322Xs_UU0AXiX9VNoe3OjZqj-EmFUAkvqfkVj5cXt...,JUNGLE,JUNGLE,Vi,6535,11,4,1,1,3,...,6161,304.100253,93,6.5,1,False,True,False,NaN,2022.0
2,2W_zqCNWa1-3zcBCzzoTXjZg_x1lbmV4224tpSRDQh5dH9...,MIDDLE,MIDDLE,Corki,8902,12,4,3,0,1,...,6974,344.227771,140,42,1,False,True,False,NaN,2022.0
3,6FZHxzDQzUXFSTaNXHdJYhiPRGMh1dC74Uns4RbgtLqhg-...,BOTTOM,BOTTOM,Sivir,8561,4,7,4,0,6,...,8588,423.862195,158,43,2,False,True,False,NaN,2022.0
4,A7p3TM0ZlmOWclAHCxcUXw1tyd13cy8-EJ4vkCMFNEu0cz...,UTILITY,UTILITY,Xerath,6240,14,4,4,0,4,...,7070,348.953532,19,9,2,False,True,False,NaN,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,QxffUyKLIHztu5DPi06OglE9Sf8Gr2NdsNY1d7EhFRfJpe...,TOP,TOP,LeeSin,7324,12,4,3,8,3,...,6656,317.423426,80,17,1,False,True,False,NaN,2097.0
326,7laSMnqFaZQgu3zqX_GVtjihk_AykGaA-0xIwjOB_20C1G...,JUNGLE,JUNGLE,Zac,5613,11,4,1,9,2,...,5155,245.845942,66,5,1,False,True,False,NaN,2097.0
327,MmWFm-YgIIxp0naNdqhU4hMmW00aI9V8dVM5mCQDdXsipx...,MIDDLE,MIDDLE,Yasuo,9404,14,4,6,6,4,...,10991,524.114813,151,65.0,1,False,True,False,NaN,2097.0
328,tPblUi0-8C2VmSudF5TeoPjvU2ifuXGZfYDHQHGDiirJ7L...,BOTTOM,UTILITY,Jhin,6091,7,4,1,8,3,...,5339,254.619547,70,40,1,False,True,False,NaN,2097.0
329,l-6JCldYBHcVxUXYDB6veikJ1eWmnanwihKJ1DxpzfIZEb...,UTILITY,UTILITY,Yuumi,4210,14,3,0,7,5,...,4459,212.627914,5,0,0,False,True,False,NaN,2097.0

#### 30분 ~ 40분 사이 종료된 게임

In [185]:
# 20게임이 존재한다.
game_played3040 = game_df[(3000<= game_df['timePlayed']) & (game_df['timePlayed'] < 4000)].reset_index(drop=True)
game_played3040

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timeplayed,timePlayed
0,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Akali,17035,4,12,5,10,4,...,11279,292.662528,167,3,0,False,False,False,NaN,3853.0
1,ef8EdZNmTuHH49lNib4mUFIWu-a60p8EvU-K1e9dzXXHQn...,JUNGLE,JUNGLE,Taliyah,17337,11,4,3,11,7,...,13305,345.221804,219,40.3,1,False,False,False,NaN,3853.0
2,4QnucqF7Qx3g6qdDWKZm8naW8QU2rIU11xPOcMRq5XbjFm...,MIDDLE,MIDDLE,Yone,19124,14,4,9,10,8,...,16345,424.098371,237,96.0,1,False,False,False,NaN,3853.0
3,aOAvT9veq32BJqJZaAv4RU9SZS5pkeNXjZKT9VzQD9j8m0...,BOTTOM,BOTTOM,Kalista,17249,7,4,13,9,8,...,18717,485.660739,284,62.8,2,False,False,False,NaN,3853.0
4,eqzWrrEr4D_zWSjTyf3VDSvffdonhAUGA2VqTHu46QD3YO...,UTILITY,UTILITY,MissFortune,14933,4,3,3,9,15,...,12123,314.549904,58,26.4,3,False,False,False,NaN,3853.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,YYD-vZSBRgTjGuiw6PFuQBkq_jWg4Gs1qd3QMNzxfpNnBS...,TOP,TOP,Nasus,15778,4,12,6,4,4,...,12352,399.182742,192,35.05,2,False,False,False,NaN,3093.0
196,2Oz57YFmjbhaQ901AdAur8KCg_Yrihi6Q43hA66isY2Zdi...,JUNGLE,JUNGLE,Vi,13183,11,4,7,11,9,...,11292,364.925387,115,3,1,False,False,False,NaN,3093.0
197,pEl9IfL_Dvj7AVHiYUxXGONzTJkYe02DkHRhx7soMjA3Tt...,MIDDLE,MIDDLE,Yasuo,9266,14,4,0,15,2,...,7362,237.938166,106,1,0,False,False,False,NaN,3093.0
198,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Jhin,12242,4,7,7,6,7,...,13746,444.223697,189,17,1,False,False,False,NaN,3093.0
199,GUAe7Jq7-2ZVXBRX1uwaXr_zzq9d_HHQ0mpMIk1ImsC_Gu...,UTILITY,UTILITY,Swain,11050,14,4,4,12,5,...,8337,269.445539,36,6.5,1,False,False,False,NaN,3093.0

#### 40분 이후에 종료된 게임

In [187]:
# 3게임이 존재한다. 
game_played40up = game_df[4000 < game_df['timePlayed']].reset_index(drop=True)
game_played40up

,puuid,teamPosition,individualPosition,champName,champExp,summoner_spell1,summoner_spell2,kills,deaths,assists,...,goldEarned,goldPerMin,totalCs,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,gameEndedInEarlySurren,gameEndedInSurren,teamEarlySurrn,timeplayed,timePlayed
0,IlqYon3McqGJG0th5WG1bYTFyUPDUIMlScWszvvMqQt7Qd...,TOP,TOP,Poppy,25408,12,4,8,5,7,...,18877,391.931189,307,77,3,False,True,False,NaN,4815.0
1,1Ki4PlEmbDX2h5__VdSYZA5tXea8oJbbbq3mLcbJWTjVGa...,JUNGLE,JUNGLE,Janna,19322,11,4,1,15,22,...,12124,251.734976,98,4,1,False,True,False,NaN,4815.0
2,3twz4G44Wj1kWZMPLSrDeGxCVp8ARFprdFiEAPxNK6o0zk...,MIDDLE,MIDDLE,Akali,22563,14,4,26,9,2,...,22486,466.869134,235,26,1,False,True,False,NaN,4815.0
3,FUwkQVEcZbRUb7d_uiY9nBHK4QPca6LBO1Io4DH9Ua2icm...,BOTTOM,BOTTOM,Jinx,24119,7,4,8,8,16,...,19669,408.379721,370,150.0,2,False,True,False,NaN,4815.0
4,ihATf3I8tbukfaBkTGtNcQfQ2_0XzVGOSIWojWwTsjUHDL...,UTILITY,UTILITY,Xerath,20470,14,4,9,6,11,...,16612,344.908673,103,40,2,False,True,False,NaN,4815.0
5,Gnj1h1FYYZIqGMaPwKoetO_jbKnUvUvukKaNXUsz9uTHV8...,TOP,TOP,Jax,21418,14,4,7,13,6,...,16747,347.702385,253,20,1,False,True,False,NaN,4815.0
6,Dfl5W0HF1Y93K-sRuIeVV6pH3r7eq8zqIVB2UJ63N8CDrf...,JUNGLE,JUNGLE,Viego,20617,11,4,9,7,15,...,17344,360.108521,186,89.0,3,False,True,False,NaN,4815.0
7,bvZq5jVAvK8_TY9gKPGSKx2mXzFBVZqGfrs1IuqWvMcLZt...,MIDDLE,MIDDLE,Ziggs,23850,7,4,6,10,16,...,19079,396.125894,328,96.5,2,False,True,False,NaN,4815.0
8,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Jhin,18809,4,7,18,9,6,...,20659,428.942018,220,12,2,False,True,False,NaN,4815.0
9,8SIB8WFW_M_an1ElcXOEkw4u4gMcURUMkSusKBw12l4AUb...,UTILITY,UTILITY,Senna,19423,14,4,3,13,21,...,13826,287.058017,73,6,2,False,True,False,NaN,4815.0
10,5yJ8xCFboYwNwZUimyidRoair5WMR_SW1DjRFLBWGhhTwJ...,TOP,TOP,Fiora,23856,12,4,9,8,10,...,16936,395.835426,237,8,1,False,False,False,NaN,4278.0
11,E291zBZqRtRql6KP0F2_NIUfDIPmcL7835VBU8k9RDHjea...,JUNGLE,JUNGLE,Warwick,25204,11,4,18,7,8,...,20698,483.754373,252,4,1,False,False,False,NaN,4278.0
12,gadp9vDdTcXV-WIh3MVpkMU6ea8VNKyaGTC64HAjnrCIBS...,MIDDLE,MIDDLE,Yone,20830,14,4,5,17,6,...,16358,382.320270,278,114.6,3,False,False,False,NaN,4278.0
13,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,BOTTOM,BOTTOM,Kaisa,22885,4,7,8,5,11,...,20247,473.208208,304,70,2,False,False,False,NaN,4278.0
14,BXIMQ94m1o1ly0WaQKVgZiTOadQbbu1_4cnD4edoDr1axg...,UTILITY,UTILITY,Velkoz,17915,4,3,6,4,15,...,13577,317.335818,71,46,3,False,False,False,NaN,4278.0
15,GUUoXH6a-cINaissbtBzFJ3AWJgPeIfeeHPvPye7z_TENk...,TOP,TOP,Vladimir,20076,12,4,8,10,7,...,17249,403.133742,284,59.15,2,False,False,False,NaN,4278.0
16,BYkzdWjv_deCAODt8jck28gZNOhOl6hT2xz5mVDPgjgHs7...,JUNGLE,JUNGLE,Kayn,23044,11,4,15,12,13,...,21393,499.985497,258,54.25,3,False,False,False,NaN,4278.0
17,nvaWS0xYWNYLXcPzHB0VbWYtRv-6qJkRNTVekfcvopMhWz...,MIDDLE,MIDDLE,Zoe,18871,14,4,5,9,16,...,13710,320.444740,164,0,1,False,False,False,NaN,4278.0
18,YZh2KQBddxVNk35noGWN2DeGOTm5pJXw0oY6ilHCtXXwor...,BOTTOM,BOTTOM,Jhin,20940,4,7,10,5,12,...,16362,382.424232,242,6,1,False,False,False,NaN,4278.0
19,tKdk22uXpXtp2fIHYdb_FuW6VfoYtr_FqQ1xGiac_ZELM5...,UTILITY,UTILITY,Xerath,15460,3,4,3,10,14,...,11035,257.904655,25,0,1,False,False,False,NaN,4278.0
20,-aez0rgkPk_4dhyCZlFS6bqn474sZmPx0AxJYXb3hqE7ts...,TOP,TOP,Irelia,24517,4,12,9,12,8,...,19367,449.681995,318,81.5,1,False,True,False,NaN,4307.0
21,VaLZaQ9DX95Ipaz3ak9Xds6PqI4pcqbbRU-CUJ1pZk9Xyg...,JUNGLE,JUNGLE,Viego,18591,14,11,5,10,6,...,15512,360.162059,208,4,1,False,True,False,NaN,4307.0
22,-627VIpngOsi_wzLSlU1cAAULisGdmCf2JhEsqH2JZBXKy...,MIDDLE,MIDDLE,Ryze,26517,14,4,9,5,10,...,20584,477.932495,367,104.1,2,False,True,False,NaN,4307.0
23,NM_--7bgBVwADwHz4y4oxWBZnK-2j9yS_mjsWccvuNV2qB...,BOTTOM,BOTTOM,Vayne,23757,7,4,9,10,10,...,19172,445.150093,281,20,1,False,True,False,NaN,4307.0
24,29POe7gL5H_aVPPvyHA0SsgYDvMH2AuMR8Urss_cEBJcs5...,UTILITY,UTILITY,Nautilus,17080,14,4,2,13,13,...,10626,246.730434,48,16,1,False,True,False,NaN,4307.0
25,cQ5NsmQunQmf0Lo8WMNEx7PZpGwr5g6sbqBmYt2hYIt-72...,TOP,TOP,Gangplank,20452,4,12,7,11,9,...,16316,378.844061,244,0,0,False,True,False,NaN,4307.0
26,Q_mR383_zhXblF2UFhr3jCJpaR63kE-qeCDULnSHav96Pp...,JUNGLE,JUNGLE,RekSai,21324,11,4,5,4,9,...,14787,343.345724,235,8.0,1,False,True,False,NaN,4307.0
27,oubPodTxo8cjIfVewo0ZHLTS56PhnKyx7_FWBHJREUyVE1...,MIDDLE,MIDDLE,MasterYi,22539,14,4,11,10,8,...,17983,417.548879,268,3,1,False,True,False,NaN,4307.0
28,kBnb5fySI9dhF1WG4KeWnqT189-4vDbHG4IDfHpFZsxRpc...,BOTTOM,BOTTOM,Xerath,18815,4,7,7,7,19,...,15406,357.713085,245,35,2,False,True,False,NaN,4307.0
29,HuOM2P_aX4HkZ11Q03JcIYv8n0GTuwdCuFSmeIsmvsBJDq...,UTILITY,UTILITY,Lux,18518,4,14,20,3,11,...,16170,375.437709,67,20,3,False,True,False,NaN,4307.0

### 종료된 시간 대별, 라인별 평균 딜량, 챔피언 경험치, 골드획득을 확인한다.

In [ ]:
def gamemean(time_df):

In [189]:
game_played40up.groupby('teamPosition').mean()

,damagePerMin,teamDamagePer(%),killParticipation(%),damageTakeOnTeamPer(%),goldPerMin,timePlayed
teamPosition,,,,,,
BOTTOM,758.532973,20.333333,50.536066,16.333333,415.969559,4466.666667
JUNGLE,678.084230,17.833333,47.381286,27.000000,383.181858,4466.666667
MIDDLE,843.231130,23.166667,45.404536,19.833333,410.206902,4466.666667
TOP,767.476149,20.666667,36.256642,23.500000,394.521466,4466.666667
UTILITY,699.504360,18.166667,47.708037,13.833333,304.895884,4466.666667